### ISSUE TITLE
Aanpassen Crabpy --> adressenregister

### ISSUE THREAD

**Issue by kmillet** [OnroerendErfgoed/crabpy#104]
Crabpy zou aangepast moeten worden zodat het adressenregister wordt aangeproken. Het meest aangewezen is het aanmaken van een nieuwe gateway hiervoor.
Om dit te kunnen uitvoeren is er eerst een analyse nodig mbt het adressenregister. Ook zou er moeten nagegaan worden welke impact de invoering van de nieuwe fusiegemeenten heeft op onze toepassingen en hoe we dit eventueel via Crabpy kunnen opvangen.

**Comment by olivermay** [comment]
Eerste analyse adressenregister:

- Mapping gemaakt tussen crabpy (en exposed webservices via crabpy-pyramid) (zie xls).
- Basisregister is nog niet volledig geïmplementeerd, vraag gesteld aan informatie vlaanderen

- Zoals het basisregister nu is, is een mapping op de huidige api niet mogelijk wegens het ontbreken van een aantal gegevens:

1. Geen informatie rond gewesten
2. Gemeenten bevatten geen geometrieën (alternatief referentie gemeenten bestand, maar dit bevat enkel de vlaamse gegevens, geen bxl en wal)
3. Metadata ontbreekt, te bekijken of deze data nodig is in de toepassingen

Ook gevraagd aan AIV of data nog beschikbaar zal komen in een toekomstige versie.
[Migratie CRAB - Basisregister.xlsx](https://github.com/OnroerendErfgoed/crabpy/files/2265925/Migratie.CRAB.-.Basisregister.xlsx)

**Comment by olivermay** [comment]
De nieuwe fusiegemeenten:

- er zijn (test) lijsten beschikbaar met alle wijzigingen in de adressen, mid december zullen er definitieve lijsten beschikbaar zijn: https://overheid.vlaanderen.be/CRAB-Gemeentelijke-fusies
- door de fusie zullen er ook wijzigingen zijn aan de deelgemeenten, deelgemeenten worden door Informatie Vlaanderen niet ontsloten, deze (nieuwe) gegevens zullen we elders moeten halen (statbel, rijksregister) voor het up-to-date brengen van deelgemeenten.json
- na de fusie dienen we een aantal update-scripts te laten lopen om de adresdata in de databanken up-to-date te brengen. 

TODO:
- inventaris maken van alle databanken die adresgegevens opslaan, 
- bepalen welke data aangepast moet worden, vb. wordt het historisch adres of het huidig adres bedoeld.

**Comment by koenedaele** [comment]
> caching herbekijken
> gewoon decorators en dogpile.null indien niet aanwezig
> centrale Redis cache voor alle apps

Ik denk niet dat dit een goed idee is? Dan kan ik dat niet meer configureren vanuit een script of op een andere plaats. Of zie ik iets over het hoofd? CRABpy zou implementatie onafhankelijk moeten kunnen werken
