### ISSUE TITLE
Testen falen sinds het binnen halen van de volledige geometrie

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/crabpy#112]
dag @cahytinne,

Indien je hier nog tijd voor hebt, de testen falen sinds https://github.com/OnroerendErfgoed/crabpy/commit/10e30763f2ecfba6d33b4ea58a37f753a49eaf87 (https://github.com/OnroerendErfgoed/crabpy/pull/99). Kan jij deze eens nakijken?

**Comment by cahytinne** [comment]
Ik heb de testdata aangepast en lokaal leek het te werken.
Nu krijg ik 
```
url = 'https://geoservices.informatievlaanderen.be/capakey/api/v1/municipality/44021/department/44021/section/A/parcel', headers = {'Accept': 'application/json'}, params = {'data': 'adp'}

    def capakey_rest_gateway_request(url, headers={}, params={}):
        '''
        Utility function that helps making requests to the CAPAKEY REST service.
    
        :param string url: URL to request.
        :param dict headers: Headers to send with the URL.
        :param dict params: Parameters to send with the URL.
        :returns: Result of the call.
        '''
        try:
            res = requests.get(url, headers=headers, params=params)
            res.raise_for_status()
            return res
        except requests.ConnectionError as ce:
            raise GatewayRuntimeException(
                'Could not execute request due to connection problems:\n%s' % repr(ce),
                ce
            )
        except requests.HTTPError as he:
>           raise GatewayResourceNotFoundException()
E           crabpy.gateway.exception.GatewayResourceNotFoundException

```
, dus denk ik dat er bij de service zelf iets hangt.

**Comment by cahytinne** [comment]
Eenmaal de service terug online, slagen de testen weer.

**Comment by goessebr** [comment]
> Ik heb de testdata aangepast en lokaal leek het te werken.

@cahytinne, Heb jij dit gepushed?

Niet meer voor jou maar voor een volgende ontwikkelaar:
We kunnen beter een definitieve oplossing voorzien want https://geoservices.informatievlaanderen.be/capakey/api/v1/municipality/44021/department/44809/section/I/parcel?data=adp lijkt nogal problematisch

Het is een call die heel lang duurt maar uiteindelijk wel werkt via mijn browser, misschien moeten die request gewoon mocken.

**Comment by goessebr** [comment]
aanpassingen gevonden in https://github.com/OnroerendErfgoed/crabpy/pull/115. Testen werken daar inderdaad. Die call blijft een potentieel probleem maar works for now
