### ISSUE TITLE
Mocken van calls naar externe url's bij testen

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/crabpy#118]
Komt uit https://github.com/OnroerendErfgoed/crabpy/issues/112#issuecomment-449353233

Onze testen zijn op dit moment afhankelijk van de URL https://geoservices.informatievlaanderen.be/capakey/api/v1. Dit zorgt op geregelde tijdstippen voor onverwacht falende testen omdat het antwoord op de URL er niet door komt of te lang op zich laat wachten.

Idealiter zijn we onafhankelijk van calls naar buiten

**Comment by koenedaele** [comment]
Ik denk dat ze ondertussen ook al een paar versies verder zitten met die service. Misschien moeten we eens aanpassen ook.

**Comment by koenedaele** [comment]
Het enige nuttige aan die tests die de service aanroepen is dat je zo makkelijk kunt checken of de andere service down is of zijn API gewijzigd heeft. Maar dat is eigenlijk een integratietest en geen unit test.
