### ISSUE TITLE
Switchen naar v2 van de capakey REST-API

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/crabpy#120]
Om een langlopend probleem te kunnen oplossen. Het gebeurt soms dat de WFS van het GRB perceelsnummers terugstuurt die niet bestaan wanneer opgevraagd via de capakey REST-API.

Uit een mail van AIV:

> Om de de actuele perceelsgegevens (ADP) van het GRB te verkrijgen via de capakey service zijn twee bijkomende (niet default) parameters nodig.
> 
> Met name data= adp en status=actual. De default waarden voor deze parameters zijn cadgis en fiscal. Dit alles heeft te maken met de verschillende verschijningsvormen van percelen.

Die data adp hadden we al aangepast. De status zouden we nu ook willen toevoegen en op actual zetten. Ik merk echter dat die enkel beschikbaar is voor v2. 

Versie 1:

https://geoservices.informatievlaanderen.be/capakey/api/v1/Help
https://geoservices.informatievlaanderen.be/capakey/api/v1/swagger

Versie 2:

https://geoservices.informatievlaanderen.be/capakey/api/v2/Help
https://geoservices.beta.informatievlaanderen.be/capakey/api/v2/swagger

API blijft op die ene optionele parameter na volledig gelijk dus ik zou gewoon de url aanpassen en voor alle parcel services, dat zijn er normaal 4, de parameter status=actual meesturen.

@koenedaele: Akkoord voor deze werkwijze?

**Comment by koenedaele** [comment]
Klinkt goed.
