### ISSUE TITLE
suds wordt (te) oud

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/crabpy#160]
We gebruiken suds-jurko als soap client. Is sinds 2014 niet geupdate. Zit vol python 2 code en hangt af van een library binnen python `2to3` om bij het installeren van de library in een python 3 omgeving automatisch de code python 3 compatibel te maken.

Dit was een gesupporteerde feature binnen `setuptools`. Maar bij de nieuwe setsuptools is die (eerst deprecated geweest en later is de) support verwijderd.
https://github.com/pypa/setuptools/issues/2086

Gevolg is dat wij bij onze projecten die crabpy/suds gebruiken ook niet de nieuwste setuptools kunnen gebruiken.

De error die je mogelijk te zien krijgt is
```
    from crabpy_pyramid import ICapakey
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/crabpy_pyramid/__init__.py:7: in <module>
    from crabpy.client import crab_factory
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/crabpy/client.py:13: in <module>
    from suds.client import Client
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/suds/__init__.py:28: in <module>
    from version import __build__, __version__
E   ModuleNotFoundError: No module named 'version'
```
Bij nieuwe virtualenvs vanaf 5 september!
![image](https://user-images.githubusercontent.com/4599667/132200838-ccf0578f-09a9-4cf8-8b8f-7e164d8afe09.png)

@OnroerendErfgoed/applicatiebeheerders Ik tag jullie omdat jullie dit mogelijks zullen voorhebben bij deploys, als de virtualenv nieuw is.
Workaround is `pip install setuptools==57.5.0` in de virutalenv te doen.

**Comment by cedrikv** [comment]
ideaal voor als ee nsprint zodner tickets dreigt te vallen. Kan je er een (ruwe) estimate op plakken?

**Comment by Wim-De-Clercq** [comment]
goh, kweet het niet goed. Deze 2 files ken ik eigenlijk niet, en ik zie niet welk project die gebruikt (Ik hoop eigenlijk dat we die gewoon kunnen deleten)
https://github.com/OnroerendErfgoed/crabpy/blob/master/crabpy/wsa.py
https://github.com/OnroerendErfgoed/crabpy/blob/master/crabpy/wsse.py

Als we die 2 even negeren is de change hier eigenlijk heel klein op `suds` door `zeep` te veranderen. Gelijk 2-3 puntjes maar.
De grotere changes zouden eerder bij crabpy_pyramid zitten, die de client gebruikt. Maar op het eerste zicht lijken zelfs daar niet echt changes nodig te zijn ... als ik eens door de readme van `zeep` kijk en vergelijk met onze code.

Omdat ik die 2 files niet ken, zou  ik er dan een 3 op zetten.

**Comment by Wim-De-Clercq** [comment]
Zoals emrys heeft gemeld bestaat er een "suds-py3" library. We zullen die gebruiken in  de plaats voor nu. Is eenvoudige upgrade.
