### ISSUE TITLE
Overschakelen naar nieuwe AGIV services

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/crabpy#183]
Zie https://github.com/OnroerendErfgoed/geoportaal/issues/1221 voor meer context.

scope:
> https://geoservices.informatievlaanderen.be/capakey/api/v2

vervangen door
> https://geo.api.vlaanderen.be/capakey/v2

**Comment by vancamti** [comment]
header fix van static_map met user-agent moet hier ook nog

**Comment by vancamti** [comment]
Zie #190
