### ISSUE TITLE
Update deelgemeenten na gemeentefusies 2025

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/crabpy#260]
gelijkaardig aan https://github.com/OnroerendErfgoed/crabpy/issues/110

Na release van https://github.com/OnroerendErfgoed/deelgemeenten/issues/9

**Comment by goessebr** [comment]
De nieuwe release van deelgemeenten (met fix voor https://github.com/OnroerendErfgoed/deelgemeenten/issues/9) is gereleased

**Comment by vancamti** [comment]
script is wat outdated mee in scope is dus script terug functioneel maken
