### ISSUE TITLE
Extend docs

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/crabpy#59]
documentation: extend API (modules) :
- [ ] API documentation through autodoc

**Comment by koenedaele** [comment]
@dieuska Not sure what you're talking about here. As far as I can see, the modules are fairly well documented?

**Comment by dieuska** [comment]
Issue not relevant: The autodoc did not appear when I built the docs locally.

So ticket can be closed (I do not have the rights to close the ticket)

**Comment by dieuska** [comment]
ticket can be closed. Autodoc did not appear when i built docs locally,
