### ISSUE TITLE
Filteren van settings die leeg of ongeldig zijn

### ISSUE THREAD

**Issue by kmillet** [OnroerendErfgoed/crabpy#66]
Als ik de volgende settings leeg laat, geeft urllib fouten:

- crabpy.proxy.http = 
- crabpy.proxy.https = 

Kan er gemaakt worden dat crabpy deze lege of ongeldige settings filtert?

**Comment by koenedaele** [comment]
Not an issue with CRABpy. More of a problem with crabpy_pyramid.
