### ISSUE TITLE
upgraden capakey rest service

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/crabpy#78]
De capakey rest service van Informatie Vlaanderen versie 0.1(https://geoservices.informatievlaanderen.be/capakey/api/v0.1) is niet langer bereikbaar. Deze moet aangepast worden naar versie 1 (https://geoservices.informatievlaanderen.be/capakey/api/v1)

Meer info: https://overheid.vlaanderen.be/capakey-rest-service

/cc @cedrikv  @koenedaele

**Comment by koenedaele** [comment]
Ook handige communicatie van AIV...

**Comment by goessebr** [comment]
Inderdaad.. 
Lokaal getest en alles werkt opnieuw perfect. Ik ga releasen en deployen
