### ISSUE TITLE
Bij get perceel de mogelijkheid bieden om de volledige geometrie af te halen

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/crabpy#96]
Op dit moment haalt hijg enkel de bounding box binnen. De mogelijkheid bieden om de volledige geometrie binnen te trekken of dit gewoon default instellen.

**Comment by cahytinne** [comment]
In https://github.com/OnroerendErfgoed/crabpy/blob/master/crabpy/gateway/capakey.py de request parameter `'geometry': 'bbox'` vervangen door  `'geometry': 'full'`
